<?php
// app/Http/Requests/InitiateTransactionRequest.php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Handles all validation for the transaction creation endpoint.
 *
 * Single Responsibility: this class's only job is validation.
 * Keeps the controller clean and validation logic reusable.
 */
class InitiateTransactionRequest extends FormRequest
{
    /**
     * Only authenticated merchants can initiate transactions.
     * This ties into Laravel Sanctum — the route middleware handles auth,
     * this just confirms the user has the 'merchant' ability.
     */
    public function authorize(): bool
    {
        // Check that the user is authenticated AND has a merchant profile
        return $this->user() !== null
            && $this->user()->merchant !== null;
    }

    /**
     * Define all validation rules.
     *
     * These rules protect the API from malformed or malicious input.
     */
    public function rules(): array
    {
        return [
            // The UUID can be generated by the client device (for offline support)
            'id'             => 'sometimes|uuid|unique:transactions,id',

            // Amount in centavos (minimum 1 centavo = PHP 0.01)
            // max:10000000 = PHP 100,000 (reasonable max for MSME)
            'amount_centavos' => 'required|integer|min:1|max:10000000',

            // ISO 4217 codes: PHP, USD, SGD, etc.
            'currency'       => 'required|string|size:3|in:PHP,USD,SGD,EUR',

            'payment_method' => 'required|string|in:qr_code,nfc,manual_entry',
            'notes'          => 'nullable|string|max:500',

            // Metadata is optional additional context from the device
            'metadata'             => 'nullable|array',
            'metadata.latitude'    => 'nullable|numeric|between:-90,90',
            'metadata.longitude'   => 'nullable|numeric|between:-180,180',
            'metadata.device_id'   => 'nullable|string|max:100',
        ];
    }

    /**
     * Custom, user-friendly error messages.
     * Instead of "amount_centavos must be an integer", show something clearer.
     */
    public function messages(): array
    {
        return [
            'amount_centavos.required' => 'Payment amount is required.',
            'amount_centavos.min'      => 'Minimum payment amount is PHP 0.01.',
            'amount_centavos.max'      => 'Maximum payment amount is PHP 100,000.',
            'currency.in'              => 'Unsupported currency. Use PHP, USD, SGD, or EUR.',
        ];
    }
}