<?php
// database/migrations/2025_01_01_000004_create_fraud_flags_table.php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Stores every fraud signal detected for a transaction.
     * One transaction can trigger multiple fraud rules at once.
     * This design lets you audit why a transaction was flagged.
     */
    public function up(): void
    {
        Schema::create('fraud_flags', function (Blueprint $table) {
            $table->uuid('id')->primary();

            // Which transaction triggered this flag
            $table->foreignUuid('transaction_id')
                  ->constrained('transactions')
                  ->onDelete('cascade');

            // Which rule triggered the flag (maps to RuleEngine constants)
            $table->string('rule_triggered');

            // How suspicious is this? 0.0 = safe, 1.0 = definitely fraud
            // Stored as decimal to avoid float imprecision
            $table->decimal('risk_score', 4, 3)->default(0.000);

            // Was this generated by rule engine or AI?
            $table->enum('source', ['rule_engine', 'ai_agent', 'manual']);

            // Human-readable explanation of why it was flagged
            $table->text('reason');

            // Was this flag reviewed and resolved by an admin?
            $table->boolean('resolved')->default(false);
            $table->timestamp('resolved_at')->nullable();

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('fraud_flags');
    }
};